runtime: python27
service: default
threadsafe: true

handlers:
- url: /
 static_files:index.html
 upload:index.html
 
- url:/styles/
 static_dir:styles
	
- url:/assets/img
 static_dir:assets/img

- url:/js/
 static_dir:js